//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ArrayOfTaskBase {
    
    private ArrayOfTaskBaseTaskBase[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaskBase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ArrayOfTaskBaseTaskBase[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArrayOfTaskBaseTaskBase {
    
    private string taskItemIdField;
    
    private string failureCausesAllStopField;
    
    private string descriptionField;
    
    private string taskGroupIdField;
    
    private string taskTypeIdField;
    
    private string sequenceField;
    
    private string taskSucceededField;
    
    private string xmlPathAndFileNameField;
    
    private string nodeToChangeField;
    
    private string attributeKeyField;
    
    private string attributeKeyValueField;
    
    private string attributeToChangeField;
    
    private string attributeToChangeValueField;
    
    private string sourcePathField;
    
    private string sourceFileNameField;
    
    private string destinationPathField;
    
    private string dosExecutableField;
    
    private string parametersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaskItemId {
        get {
            return this.taskItemIdField;
        }
        set {
            this.taskItemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FailureCausesAllStop {
        get {
            return this.failureCausesAllStopField;
        }
        set {
            this.failureCausesAllStopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaskGroupId {
        get {
            return this.taskGroupIdField;
        }
        set {
            this.taskGroupIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaskTypeId {
        get {
            return this.taskTypeIdField;
        }
        set {
            this.taskTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaskSucceeded {
        get {
            return this.taskSucceededField;
        }
        set {
            this.taskSucceededField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string XmlPathAndFileName {
        get {
            return this.xmlPathAndFileNameField;
        }
        set {
            this.xmlPathAndFileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NodeToChange {
        get {
            return this.nodeToChangeField;
        }
        set {
            this.nodeToChangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttributeKey {
        get {
            return this.attributeKeyField;
        }
        set {
            this.attributeKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttributeKeyValue {
        get {
            return this.attributeKeyValueField;
        }
        set {
            this.attributeKeyValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttributeToChange {
        get {
            return this.attributeToChangeField;
        }
        set {
            this.attributeToChangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttributeToChangeValue {
        get {
            return this.attributeToChangeValueField;
        }
        set {
            this.attributeToChangeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SourcePath {
        get {
            return this.sourcePathField;
        }
        set {
            this.sourcePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SourceFileName {
        get {
            return this.sourceFileNameField;
        }
        set {
            this.sourceFileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DestinationPath {
        get {
            return this.destinationPathField;
        }
        set {
            this.destinationPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DosExecutable {
        get {
            return this.dosExecutableField;
        }
        set {
            this.dosExecutableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
}
