//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestoViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrestoViewModel.ViewModelResources", typeof(ViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be installed on {1}.
        /// </summary>
        internal static string AppWillBeInstalledOnAppServer {
            get {
                return ResourceManager.GetString("AppWillBeInstalledOnAppServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items could not be imported. Please verify that the file is in the correct format..
        /// </summary>
        internal static string CannotImport {
            get {
                return ResourceManager.GetString("CannotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected custom variable group cannot be associated with a server because it&apos;s already associated with an application..
        /// </summary>
        internal static string CannotUseGroup {
            get {
                return ResourceManager.GetString("CannotUseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        internal static string ConfirmCaption {
            get {
                return ResourceManager.GetString("ConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("ConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want {0} to be installed on {1}?.
        /// </summary>
        internal static string ConfirmInstallAppOnAppServerMessage {
            get {
                return ResourceManager.GetString("ConfirmInstallAppOnAppServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection could not be made to the database. Please verify that the database is running and try again. See the log for more detail..
        /// </summary>
        internal static string DatabaseConnectionFailureMessage {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid operation occurred on the database. Sometimes this is because of an unsupported class hierarchy change..
        /// </summary>
        internal static string DatabaseInvalidOperation {
            get {
                return ResourceManager.GetString("DatabaseInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings refreshed..
        /// </summary>
        internal static string GlobalSettingsRefreshed {
            get {
                return ResourceManager.GetString("GlobalSettingsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings saved..
        /// </summary>
        internal static string GlobalSettingsSaved {
            get {
                return ResourceManager.GetString("GlobalSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation summary list refreshed..
        /// </summary>
        internal static string InstallationListRefreshed {
            get {
                return ResourceManager.GetString("InstallationListRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not saved because another user has changed it. Please refresh and try again..
        /// </summary>
        internal static string ItemCannotBeSavedConcurrency {
            get {
                return ResourceManager.GetString("ItemCannotBeSavedConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been exported..
        /// </summary>
        internal static string ItemExported {
            get {
                return ResourceManager.GetString("ItemExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Not Saved.
        /// </summary>
        internal static string ItemNotSavedCaption {
            get {
                return ResourceManager.GetString("ItemNotSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved..
        /// </summary>
        internal static string ItemSaved {
            get {
                return ResourceManager.GetString("ItemSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log message list refreshed..
        /// </summary>
        internal static string LogMessagesRefreshed {
            get {
                return ResourceManager.GetString("LogMessagesRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping items refreshed..
        /// </summary>
        internal static string PingItemsRefreshed {
            get {
                return ResourceManager.GetString("PingItemsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Presto self-updating service could not be installed. Please make sure that app has been assigned to this server. You can also check the log for details on this error..
        /// </summary>
        internal static string PrestoUpdaterCouldNotBeInstalled {
            get {
                return ResourceManager.GetString("PrestoUpdaterCouldNotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry.
        /// </summary>
        internal static string TaskInvalidEntryCaption {
            get {
                return ResourceManager.GetString("TaskInvalidEntryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task has an invalid entry. Please correct and try saving again..
        /// </summary>
        internal static string TaskInvalidEntryMessage {
            get {
                return ResourceManager.GetString("TaskInvalidEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When importing legacy tasks, we encountered a legacy task type that was not expected: {0}..
        /// </summary>
        internal static string UnexpectedLegacyTask {
            get {
                return ResourceManager.GetString("UnexpectedLegacyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables resolved. Number of problems found: {0}. {1}.
        /// </summary>
        internal static string VariablesResolved {
            get {
                return ResourceManager.GetString("VariablesResolved", resourceCulture);
            }
        }
    }
}
